name: Build
on:
  push:
    paths:
      - 'PKGBUILD'
      - 'config'
  workflow_dispatch:

jobs:
  build:
    name: linux-aegis-${{ matrix.profile }}
    strategy:
      matrix:
        profile: [offensive, hardened]
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup build environment
      run: |
        pacman-key --init
        pacman -Syu --noconfirm
        useradd builder -m
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chmod -R a+rw .
        sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j$(nproc) -l$(nproc)"/g' /etc/makepkg.conf
        sed -i 's/#PACKAGER=".*"/PACKAGER="Athena OS GitHub Actions"/g' /etc/makepkg.conf

    - name: Build (${{ matrix.profile }})
      env:
        _aegis_profile: ${{ matrix.profile }}
        _use_llvm_lto: full
        _processor_opt: generic
        #_use_kcfi: ${{ matrix.profile == 'hardened' && 'yes' || 'no' }}
        _use_kcfi: 'no'
      run: |
        sudo -H -E -u builder makepkg --skipchecksums --syncdeps --noconfirm

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: linux-aegis-${{ matrix.profile }}
        path: "*.pkg.tar.zst*"
